# Generated by Django 4.2.27 on 2026-01-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilapp', '0002_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('questions_reponses', models.JSONField(default=list)),
                ('score_completion', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
